version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    depends_on:
      - db
    ports:
      - "50051:50051"

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    depends_on:
      - server
    ports:
      - "50052:50052"
  
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: # Здесь объявляем том